gui:
  scrollHeight: 10
  mouseEvents: false
  language: en
  theme:
    selectedLineBgColor:
      - white
  nerdFontsVersion: 3
git:
  branchLogCmd: 'git log --graph --color=always --date=human --format="%C(#e3c78a)%h%C(#ff5454)%d%C(reset) - %C(#36c692)(%ad)%C(reset) %s %C(#80a0ff){%an}%C(reset)" {{branchName}} --'
